---
title: "Univariate and Bivariate Stats and Graphics"
---

## Univariate and Bivariate Stats and Graphics

This workshop will be held on Monday July 23, 2018.

The focus of this workshop is on visualizing variables and computing summary statistics for those variables in your dataset one (univariate) or two (bivariate) at a time. This workshop will introduce both base R graphical approaches and `ggplot2` graphics.

## Data for Workshop

Download the H.E.L.P dataset for this workshop by clicking [here](https://github.com/melindahiggins2000/RWorkshops_EmorySON/blob/master/help.Rdata?raw=true)

You can learn more about the H.E.L.P. _(Health Evaluation and Linkage to Primary Care)_ dataset at [https://nhorton.people.amherst.edu/sasr2/datasets.php](https://nhorton.people.amherst.edu/sasr2/datasets.php)

## R Code (Script) for Workshop

Download the R Code "Script" for today's workshop by clicking [here](https://github.com/melindahiggins2000/RWorkshops_EmorySON/raw/master/uniBivariate.R).

## R Packages Needed

* `dplyr` [https://cran.r-project.org/web/packages/dplyr/](https://cran.r-project.org/web/packages/dplyr/), also see [https://www.tidyverse.org/packages/](https://www.tidyverse.org/packages/)
* `ggplot2` [https://cran.r-project.org/web/packages/ggplot2/](https://cran.r-project.org/web/packages/ggplot2/), also see [https://www.tidyverse.org/packages/](https://www.tidyverse.org/packages/)
* `Hmisc` [https://cran.r-project.org/web/packages/Hmisc/](https://cran.r-project.org/web/packages/Hmisc/)
* `psych` [https://cran.r-project.org/web/packages/psych/](https://cran.r-project.org/web/packages/psych/)
* `pastecs` [https://cran.r-project.org/web/packages/pastecs/](https://cran.r-project.org/web/packages/pastecs/)
* `gmodels` [https://cran.r-project.org/web/packages/gmodels/](https://cran.r-project.org/web/packages/gmodels/)
* `car` [https://cran.r-project.org/web/packages/car/](https://cran.r-project.org/web/packages/car/)
* optional
    + `ggpubr` [https://cran.r-project.org/web/packages/ggpubr/](https://cran.r-project.org/web/packages/ggpubr/)
    + `e1071` [https://cran.r-project.org/web/packages/e1071/](https://cran.r-project.org/web/packages/e1071/)
    + `violinmplot` [https://cran.r-project.org/web/packages/violinmplot/](https://cran.r-project.org/web/packages/violinmplot/)

## Recording

The video recording for this workshop will be posted within a week of the workshop.






